# Generated by Django 3.0.2 on 2021-07-09 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='login',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guest',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
